/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dokladoz;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextPane;

/**
 *
 * @author Кузьмич
 */
public class OsnFrame extends javax.swing.JFrame {

    /**
     * Creates new form OsnFrame
     */
    public OsnFrame() {
        initComponents();
        setLocationRelativeTo(this);//окно в центр экрана
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSformirovMSG = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        areaVuvodMSG = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        poleNomZeli = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        poleKoord = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        ktoStrelial = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        poleKalibr = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        poleTipBK = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        poleRashod = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        poleTipZeli = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Доклад Оз");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("№ Цели");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Координаты цели");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Кто выполнял залдачу");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Калибр");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Тип боеприпаса");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Расход");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Тип цели");

        btnSformirovMSG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSformirovMSG.setText("Сформировать сообщение");

        areaVuvodMSG.setColumns(20);
        areaVuvodMSG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        areaVuvodMSG.setLineWrap(true);
        areaVuvodMSG.setRows(5);
        jScrollPane8.setViewportView(areaVuvodMSG);

        poleNomZeli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane9.setViewportView(poleNomZeli);

        poleKoord.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane10.setViewportView(poleKoord);

        ktoStrelial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane11.setViewportView(ktoStrelial);

        poleKalibr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane12.setViewportView(poleKalibr);

        poleTipBK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane13.setViewportView(poleTipBK);

        poleRashod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane14.setViewportView(poleRashod);

        poleTipZeli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane15.setViewportView(poleTipZeli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSformirovMSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane13)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane14)))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSformirovMSG)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OsnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OsnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OsnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OsnFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OsnFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaVuvodMSG;
    private javax.swing.JButton btnSformirovMSG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane ktoStrelial;
    private javax.swing.JTextPane poleKalibr;
    private javax.swing.JTextPane poleKoord;
    private javax.swing.JTextPane poleNomZeli;
    private javax.swing.JTextPane poleRashod;
    private javax.swing.JTextPane poleTipBK;
    private javax.swing.JTextPane poleTipZeli;
    // End of variables declaration//GEN-END:variables

    public JTextArea getAreaVuvodMSG() {
        return areaVuvodMSG;
    }

    public JButton getBtnSformirovMSG() {
        return btnSformirovMSG;
    }

    public void setAreaVuvodMSG(String msg) {
        this.areaVuvodMSG.setText(msg);
    }

    public JTextPane getKtoStrelial() {
        return ktoStrelial;
    }

    public void setKtoStrelial(JTextPane ktoStrelial) {
        this.ktoStrelial = ktoStrelial;
    }

    public JTextPane getPoleKalibr() {
        return poleKalibr;
    }

    public void setPoleKalibr(JTextPane poleKalibr) {
        this.poleKalibr = poleKalibr;
    }

    public JTextPane getPoleKoord() {
        return poleKoord;
    }

    public void setPoleKoord(JTextPane poleKoord) {
        this.poleKoord = poleKoord;
    }

    public JTextPane getPoleNomZeli() {
        return poleNomZeli;
    }

    public void setPoleNomZeli(JTextPane poleNomZeli) {
        this.poleNomZeli = poleNomZeli;
    }

    public JTextPane getPoleRashod() {
        return poleRashod;
    }

    public void setPoleRashod(JTextPane poleRashod) {
        this.poleRashod = poleRashod;
    }

    public JTextPane getPoleTipBK() {
        return poleTipBK;
    }

    public void setPoleTipBK(JTextPane poleTipBK) {
        this.poleTipBK = poleTipBK;
    }

    public JTextPane getPoleTipZeli() {
        return poleTipZeli;
    }

    public void setPoleTipZeli(JTextPane poleTipZeli) {
        this.poleTipZeli = poleTipZeli;
    }


}
